services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: erbotli
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: erbotli
    ports:
      - '5432:5432'
    volumes:
      - erbotli_pg_data:/var/lib/postgresql/data

volumes:
  erbotli_pg_data:
